/// Cross-Chain Message Format for NFT Transfers
/// 
/// This module defines the standardized message format for cross-chain NFT transfers
/// between Solana, ZetaChain, and EVM chains (Base Sepolia, BNB Smart Chain).
/// The format ensures compatibility and data integrity across different blockchain architectures.

use anchor_lang::prelude::*;
use crate::constants::chains::*;
use crate::error::UniversalNftError;

/// Message type constants for different cross-chain operations
pub const MESSAGE_TYPE_NFT_MINT: u8 = 1;
pub const MESSAGE_TYPE_NFT_BURN: u8 = 2;
pub const MESSAGE_TYPE_NFT_TRANSFER: u8 = 3;
pub const MESSAGE_TYPE_COLLECTION_UPDATE: u8 = 4;

/// Cross-chain message format for NFT transfers
/// 
/// This struct defines the standardized format for cross-chain NFT messages.
/// It includes all necessary information to recreate an NFT on the destination chain
/// while preserving its metadata and origin information.
#[derive(AnchorSerialize, AnchorDeserialize, Clone, Debug, PartialEq)]
pub struct CrossChainNftMessage {
    /// Message type (1 = mint, 2 = burn, 3 = transfer, 4 = collection update)
    pub message_type: u8,
    
    /// Unique token ID across all chains (generated by the origin chain)
    pub token_id: u64,
    
    /// Metadata URI (IPFS, HTTP, etc.) containing NFT metadata
    pub metadata_uri: String,
    
    /// NFT name
    pub name: String,
    
    /// NFT symbol
    pub symbol: String,
    
    /// Chain ID where the NFT was originally minted
    pub origin_chain_id: u8,
    
    /// Original mint/contract address on the origin chain
    pub origin_address: [u8; 32],
    
    /// Recipient address on the destination chain
    pub recipient_address: [u8; 32],
    
    /// Timestamp when the message was created (Unix timestamp)
    pub timestamp: i64,
    
    /// Message ID for replay protection (unique identifier)
    pub message_id: [u8; 32],
    
    /// Additional metadata (optional, chain-specific)
    pub additional_metadata: Option<Vec<u8>>,
}

impl CrossChainNftMessage {
    /// Create a new cross-chain NFT message for minting
    pub fn new_mint(
        token_id: u64,
        metadata_uri: String,
        name: String,
        symbol: String,
        origin_chain_id: u8,
        origin_address: [u8; 32],
        recipient_address: [u8; 32],
        message_id: [u8; 32],
    ) -> Self {
        Self {
            message_type: MESSAGE_TYPE_NFT_MINT,
            token_id,
            metadata_uri,
            name,
            symbol,
            origin_chain_id,
            origin_address,
            recipient_address,
            timestamp: Clock::get().unwrap().unix_timestamp,
            message_id,
            additional_metadata: None,
        }
    }
    
    /// Create a new cross-chain NFT message for burning
    pub fn new_burn(
        token_id: u64,
        origin_chain_id: u8,
        origin_address: [u8; 32],
        recipient_address: [u8; 32],
        message_id: [u8; 32],
    ) -> Self {
        Self {
            message_type: MESSAGE_TYPE_NFT_BURN,
            token_id,
            metadata_uri: String::new(),
            name: String::new(),
            symbol: String::new(),
            origin_chain_id,
            origin_address,
            recipient_address,
            timestamp: Clock::get().unwrap().unix_timestamp,
            message_id,
            additional_metadata: None,
        }
    }
    
    /// Validate the message format
    pub fn validate(&self) -> Result<()> {
        // Validate message type
        require!(
            matches!(self.message_type, 1..=4),
            UniversalNftError::InvalidMessageType
        );
        
        // Validate token ID
        require!(self.token_id > 0, UniversalNftError::InvalidTokenId);
        
        // Validate origin chain ID
        require!(
            is_chain_supported(self.origin_chain_id),
            UniversalNftError::UnsupportedChainId
        );
        
        // Validate metadata URI for mint messages
        if self.message_type == MESSAGE_TYPE_NFT_MINT {
            require!(
                !self.metadata_uri.is_empty(),
                UniversalNftError::InvalidMetadataUri
            );
            require!(
                !self.name.is_empty(),
                UniversalNftError::InvalidNftName
            );
            require!(
                !self.symbol.is_empty(),
                UniversalNftError::InvalidNftSymbol
            );
        }
        
        // Validate timestamp (should be recent)
        let current_time = Clock::get()?.unix_timestamp;
        let time_diff = (current_time - self.timestamp).abs();
        require!(
            time_diff <= MAX_MESSAGE_AGE_SECONDS,
            UniversalNftError::MessageTooOld
        );
        
        Ok(())
    }
    
    /// Serialize the message to bytes for cross-chain transmission
    pub fn serialize(&self) -> Result<Vec<u8>> {
        self.try_to_vec().map_err(|_| UniversalNftError::SerializationError.into())
    }
    
    /// Deserialize the message from bytes
    pub fn deserialize(data: &[u8]) -> Result<Self> {
        // Validate data size before attempting deserialization
        if data.is_empty() {
            return Err(UniversalNftError::DeserializationError.into());
        }
        
        // Check for reasonable size limits to prevent memory issues
        if data.len() > 2048 {
            return Err(UniversalNftError::DeserializationError.into());
        }
        
        // Attempt deserialization with error handling
        Self::try_from_slice(data).map_err(|_| UniversalNftError::DeserializationError.into())
    }
    
    /// Get the message size in bytes
    pub fn size(&self) -> usize {
        self.serialize().unwrap_or_default().len()
    }
    
    /// Check if this is a mint message
    pub fn is_mint(&self) -> bool {
        self.message_type == MESSAGE_TYPE_NFT_MINT
    }
    
    /// Check if this is a burn message
    pub fn is_burn(&self) -> bool {
        self.message_type == MESSAGE_TYPE_NFT_BURN
    }
    
    /// Check if this is a transfer message
    pub fn is_transfer(&self) -> bool {
        self.message_type == MESSAGE_TYPE_NFT_TRANSFER
    }
    
    /// Check if this is a collection update message
    pub fn is_collection_update(&self) -> bool {
        self.message_type == MESSAGE_TYPE_COLLECTION_UPDATE
    }
}

/// Message format constants
pub const MAX_MESSAGE_AGE_SECONDS: i64 = 3600; // 1 hour
pub const MAX_METADATA_URI_LENGTH: usize = 200;
pub const MAX_NFT_NAME_LENGTH: usize = 32;
pub const MAX_NFT_SYMBOL_LENGTH: usize = 10;
pub const MAX_ADDITIONAL_METADATA_SIZE: usize = 1024;

/// Function selector for EVM contract calls
/// 
/// These are the 4-byte function selectors for the receiving contract functions
/// on EVM chains. They are derived from the function signatures.
pub const EVM_FUNCTION_SELECTORS: [u8; 4] = [
    0x12, 0x34, 0x56, 0x78, // Placeholder - replace with actual selectors
];

/// Encode message for EVM chain transmission
/// 
/// This function encodes the cross-chain message in a format that EVM chains
/// can interpret, including the function selector and ABI-encoded parameters.
pub fn encode_for_evm(message: &CrossChainNftMessage) -> Result<Vec<u8>> {
    let mut encoded = Vec::new();
    
    // Add function selector (placeholder - should be actual selector)
    encoded.extend_from_slice(&EVM_FUNCTION_SELECTORS);
    
    // Encode parameters according to EVM ABI
    // tokenId (uint256)
    encoded.extend_from_slice(&message.token_id.to_be_bytes());
    
    // metadataUri (string) - add length prefix
    let uri_bytes = message.metadata_uri.as_bytes();
    encoded.extend_from_slice(&(uri_bytes.len() as u32).to_be_bytes());
    encoded.extend_from_slice(uri_bytes);
    
    // name (string) - add length prefix
    let name_bytes = message.name.as_bytes();
    encoded.extend_from_slice(&(name_bytes.len() as u32).to_be_bytes());
    encoded.extend_from_slice(name_bytes);
    
    // symbol (string) - add length prefix
    let symbol_bytes = message.symbol.as_bytes();
    encoded.extend_from_slice(&(symbol_bytes.len() as u32).to_be_bytes());
    encoded.extend_from_slice(symbol_bytes);
    
    // originChainId (uint8)
    encoded.push(message.origin_chain_id);
    
    // originAddress (bytes32) - pad to 32 bytes
    encoded.extend_from_slice(&message.origin_address);
    
    // recipientAddress (bytes32) - pad to 32 bytes
    encoded.extend_from_slice(&message.recipient_address);
    
    // timestamp (uint256)
    encoded.extend_from_slice(&(message.timestamp as u64).to_be_bytes());
    
    // messageId (bytes32)
    encoded.extend_from_slice(&message.message_id);
    
    Ok(encoded)
}

/// Decode message from EVM chain format
/// 
/// This function decodes the cross-chain message from EVM ABI format
/// back to our internal message format.
pub fn decode_from_evm(data: &[u8]) -> Result<CrossChainNftMessage> {
    // Skip function selector (4 bytes)
    let mut offset = 4;
    
    // Decode tokenId (uint256) - 32 bytes
    let token_id = u64::from_be_bytes(data[offset..offset + 8].try_into().unwrap());
    offset += 32; // Skip to next parameter
    
    // Decode metadataUri (string)
    let uri_length = u32::from_be_bytes(data[offset..offset + 4].try_into().unwrap()) as usize;
    offset += 4;
    let metadata_uri = String::from_utf8(data[offset..offset + uri_length].to_vec())
        .map_err(|_| UniversalNftError::InvalidMetadataUri)?;
    offset += uri_length;
    
    // Decode name (string)
    let name_length = u32::from_be_bytes(data[offset..offset + 4].try_into().unwrap()) as usize;
    offset += 4;
    let name = String::from_utf8(data[offset..offset + name_length].to_vec())
        .map_err(|_| UniversalNftError::InvalidNftName)?;
    offset += name_length;
    
    // Decode symbol (string)
    let symbol_length = u32::from_be_bytes(data[offset..offset + 4].try_into().unwrap()) as usize;
    offset += 4;
    let symbol = String::from_utf8(data[offset..offset + symbol_length].to_vec())
        .map_err(|_| UniversalNftError::InvalidNftSymbol)?;
    offset += symbol_length;
    
    // Decode originChainId (uint8)
    let origin_chain_id = data[offset];
    offset += 1;
    
    // Decode originAddress (bytes32)
    let origin_address = data[offset..offset + 32].try_into().unwrap();
    offset += 32;
    
    // Decode recipientAddress (bytes32)
    let recipient_address = data[offset..offset + 32].try_into().unwrap();
    offset += 32;
    
    // Decode timestamp (uint256) - 32 bytes
    let timestamp = i64::from_be_bytes(data[offset..offset + 8].try_into().unwrap());
    offset += 32; // Skip to next parameter
    
    // Decode messageId (bytes32)
    let message_id = data[offset..offset + 32].try_into().unwrap();
    
    // Create message (we'll need to determine message type from context)
    let message = CrossChainNftMessage {
        message_type: MESSAGE_TYPE_NFT_MINT, // Default to mint, should be determined from context
        token_id,
        metadata_uri,
        name,
        symbol,
        origin_chain_id,
        origin_address,
        recipient_address,
        timestamp,
        message_id,
        additional_metadata: None,
    };
    
    Ok(message)
}

/// Validate message size constraints
pub fn validate_message_size(message: &CrossChainNftMessage) -> Result<()> {
    let size = message.size();
    
    require!(
        size <= CROSS_CHAIN_MAX_MESSAGE_SIZE,
        UniversalNftError::MessageTooLarge
    );
    
    require!(
        size >= CROSS_CHAIN_MIN_MESSAGE_SIZE,
        UniversalNftError::MessageTooSmall
    );
    
    Ok(())
}

/// Message size constants
pub const CROSS_CHAIN_MIN_MESSAGE_SIZE: usize = 100; // Minimum message size in bytes
pub const CROSS_CHAIN_MAX_MESSAGE_SIZE: usize = 2048; // Maximum message size in bytes

/// Error types for message format validation
#[derive(Debug)]
pub enum MessageFormatError {
    InvalidMessageType,
    InvalidTokenId,
    InvalidMetadataUri,
    InvalidNftName,
    InvalidNftSymbol,
    MessageTooOld,
    MessageTooLarge,
    MessageTooSmall,
    SerializationError,
    DeserializationError,
}

impl From<MessageFormatError> for Error {
    fn from(err: MessageFormatError) -> Self {
        match err {
            MessageFormatError::InvalidMessageType => UniversalNftError::InvalidMessageType.into(),
            MessageFormatError::InvalidTokenId => UniversalNftError::InvalidTokenId.into(),
            MessageFormatError::InvalidMetadataUri => UniversalNftError::InvalidMetadataUri.into(),
            MessageFormatError::InvalidNftName => UniversalNftError::InvalidNftName.into(),
            MessageFormatError::InvalidNftSymbol => UniversalNftError::InvalidNftSymbol.into(),
            MessageFormatError::MessageTooOld => UniversalNftError::MessageTooOld.into(),
            MessageFormatError::MessageTooLarge => UniversalNftError::MessageTooLarge.into(),
            MessageFormatError::MessageTooSmall => UniversalNftError::MessageTooSmall.into(),
            MessageFormatError::SerializationError => UniversalNftError::SerializationError.into(),
            MessageFormatError::DeserializationError => UniversalNftError::DeserializationError.into(),
        }
    }
}
