/**
 * Cross-Chain Message Format for NFT Transfers
 *
 * This module defines the TypeScript interfaces and utilities for cross-chain
 * NFT message format, ensuring consistency with the Rust implementation.
 */

export interface CrossChainNftMessage {
  /** Message type (1 = mint, 2 = burn, 3 = transfer, 4 = collection update) */
  messageType: number;

  /** Unique token ID across all chains (generated by the origin chain) */
  tokenId: number;

  /** Metadata URI (IPFS, HTTP, etc.) containing NFT metadata */
  metadataUri: string;

  /** NFT name */
  name: string;

  /** NFT symbol */
  symbol: string;

  /** Chain ID where the NFT was originally minted */
  originChainId: number;

  /** Original mint/contract address on the origin chain */
  originAddress: Uint8Array;

  /** Recipient address on the destination chain */
  recipientAddress: Uint8Array;

  /** Timestamp when the message was created (Unix timestamp) */
  timestamp: number;

  /** Message ID for replay protection (unique identifier) */
  messageId: Uint8Array;

  /** Additional metadata (optional, chain-specific) */
  additionalMetadata?: Uint8Array;
}

/**
 * Message type constants
 */
export const MESSAGE_TYPES = {
  NFT_MINT: 1,
  NFT_BURN: 2,
  NFT_TRANSFER: 3,
  COLLECTION_UPDATE: 4,
} as const;

/**
 * Chain ID constants
 */
export const CHAIN_IDS = {
  SOLANA: 1,
  BASE_SEPOLIA: 2,
  BNB_TESTNET: 3,
} as const;

/**
 * Message format constants
 */
export const MESSAGE_CONSTANTS = {
  MAX_MESSAGE_AGE_SECONDS: 3600, // 1 hour
  MAX_METADATA_URI_LENGTH: 200,
  MAX_NFT_NAME_LENGTH: 32,
  MAX_NFT_SYMBOL_LENGTH: 10,
  MAX_ADDITIONAL_METADATA_SIZE: 1024,
  MIN_MESSAGE_SIZE: 100,
  MAX_MESSAGE_SIZE: 2048,
} as const;

/**
 * Create a new cross-chain NFT message for minting
 */
export function createMintMessage(
  tokenId: number,
  metadataUri: string,
  name: string,
  symbol: string,
  originChainId: number,
  originAddress: Uint8Array,
  recipientAddress: Uint8Array,
  messageId: Uint8Array
): CrossChainNftMessage {
  return {
    messageType: MESSAGE_TYPES.NFT_MINT,
    tokenId,
    metadataUri,
    name,
    symbol,
    originChainId,
    originAddress,
    recipientAddress,
    timestamp: Math.floor(Date.now() / 1000),
    messageId,
  };
}

/**
 * Create a new cross-chain NFT message for burning
 */
export function createBurnMessage(
  tokenId: number,
  originChainId: number,
  originAddress: Uint8Array,
  recipientAddress: Uint8Array,
  messageId: Uint8Array
): CrossChainNftMessage {
  return {
    messageType: MESSAGE_TYPES.NFT_BURN,
    tokenId,
    metadataUri: '',
    name: '',
    symbol: '',
    originChainId,
    originAddress,
    recipientAddress,
    timestamp: Math.floor(Date.now() / 1000),
    messageId,
  };
}

/**
 * Validate a cross-chain NFT message
 */
export function validateMessage(message: CrossChainNftMessage): string[] {
  const errors: string[] = [];

  // Validate message type
  if (
    !Object.values(MESSAGE_TYPES).includes(message.messageType as 1 | 2 | 3 | 4)
  ) {
    errors.push('Invalid message type - must be 1-4');
  }

  // Validate token ID
  if (message.tokenId <= 0) {
    errors.push('Invalid token ID - must be greater than 0');
  }

  // Validate origin chain ID
  if (!Object.values(CHAIN_IDS).includes(message.originChainId as 1 | 2 | 3)) {
    errors.push('Unsupported chain ID');
  }

  // Validate metadata URI for mint messages
  if (message.messageType === MESSAGE_TYPES.NFT_MINT) {
    if (!message.metadataUri) {
      errors.push('Invalid metadata URI - cannot be empty');
    }
    if (!message.name) {
      errors.push('Invalid NFT name - cannot be empty');
    }
    if (!message.symbol) {
      errors.push('Invalid NFT symbol - cannot be empty');
    }
  }

  // Validate timestamp (should be recent)
  const currentTime = Math.floor(Date.now() / 1000);
  const timeDiff = Math.abs(currentTime - message.timestamp);
  if (timeDiff > MESSAGE_CONSTANTS.MAX_MESSAGE_AGE_SECONDS) {
    errors.push('Message too old - timestamp exceeds maximum age');
  }

  // Validate address lengths
  if (message.originAddress.length !== 32) {
    errors.push('Invalid origin address length - must be 32 bytes');
  }
  if (message.recipientAddress.length !== 32) {
    errors.push('Invalid recipient address length - must be 32 bytes');
  }
  if (message.messageId.length !== 32) {
    errors.push('Invalid message ID length - must be 32 bytes');
  }

  // Validate string lengths
  if (message.metadataUri.length > MESSAGE_CONSTANTS.MAX_METADATA_URI_LENGTH) {
    errors.push('Metadata URI too long');
  }
  if (message.name.length > MESSAGE_CONSTANTS.MAX_NFT_NAME_LENGTH) {
    errors.push('NFT name too long');
  }
  if (message.symbol.length > MESSAGE_CONSTANTS.MAX_NFT_SYMBOL_LENGTH) {
    errors.push('NFT symbol too long');
  }

  return errors;
}

/**
 * Check if a message is a mint message
 */
export function isMintMessage(message: CrossChainNftMessage): boolean {
  return message.messageType === MESSAGE_TYPES.NFT_MINT;
}

/**
 * Check if a message is a burn message
 */
export function isBurnMessage(message: CrossChainNftMessage): boolean {
  return message.messageType === MESSAGE_TYPES.NFT_BURN;
}

/**
 * Check if a message is a transfer message
 */
export function isTransferMessage(message: CrossChainNftMessage): boolean {
  return message.messageType === MESSAGE_TYPES.NFT_TRANSFER;
}

/**
 * Check if a message is a collection update message
 */
export function isCollectionUpdateMessage(
  message: CrossChainNftMessage
): boolean {
  return message.messageType === MESSAGE_TYPES.COLLECTION_UPDATE;
}

/**
 * Serialize a message to a buffer for cross-chain transmission
 */
export function serializeMessage(message: CrossChainNftMessage): Buffer {
  // This is a simplified serialization for testing
  // In production, this should match the Rust serialization format
  const encoder = new TextEncoder();

  const messageData = {
    messageType: message.messageType,
    tokenId: message.tokenId,
    metadataUri: message.metadataUri,
    name: message.name,
    symbol: message.symbol,
    originChainId: message.originChainId,
    originAddress: Array.from(message.originAddress),
    recipientAddress: Array.from(message.recipientAddress),
    timestamp: message.timestamp,
    messageId: Array.from(message.messageId),
    additionalMetadata: message.additionalMetadata
      ? Array.from(message.additionalMetadata)
      : undefined,
  };

  const jsonString = JSON.stringify(messageData);
  return Buffer.from(jsonString, 'utf8');
}

/**
 * Deserialize a message from a buffer
 */
export function deserializeMessage(data: Buffer): CrossChainNftMessage {
  // This is a simplified deserialization for testing
  // In production, this should match the Rust deserialization format
  const jsonString = data.toString('utf8');
  const messageData = JSON.parse(jsonString);

  return {
    messageType: messageData.messageType,
    tokenId: messageData.tokenId,
    metadataUri: messageData.metadataUri,
    name: messageData.name,
    symbol: messageData.symbol,
    originChainId: messageData.originChainId,
    originAddress: new Uint8Array(messageData.originAddress),
    recipientAddress: new Uint8Array(messageData.recipientAddress),
    timestamp: messageData.timestamp,
    messageId: new Uint8Array(messageData.messageId),
    additionalMetadata: messageData.additionalMetadata
      ? new Uint8Array(messageData.additionalMetadata)
      : undefined,
  };
}

/**
 * Generate a unique message ID
 */
export function generateMessageId(): Uint8Array {
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return array;
}

/**
 * Convert a Solana public key to a 32-byte array for cross-chain compatibility
 */
export function publicKeyToBytes(publicKey: any): Uint8Array {
  return new Uint8Array(publicKey.toBytes());
}

/**
 * Convert a 32-byte array to a Solana public key
 */
export function bytesToPublicKey(bytes: Uint8Array): any {
  const { PublicKey } = require('@solana/web3.js');
  return new PublicKey(bytes);
}
